# Generated by Django 3.2.9 on 2021-11-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211125_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SkillItem',
        ),
    ]
