# Generated by Django 3.2.9 on 2021-11-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='item',
            field=models.CharField(default='Item', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(upload_to='media'),
        ),
    ]
