# Generated by Django 3.2.9 on 2021-11-27 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_category'),
        ('users', '0008_auto_20211126_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
    ]
