# Generated by Django 3.2.9 on 2021-11-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211130_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.AutoField(primary_key=True,serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
