# Generated by Django 3.2.9 on 2021-11-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='message',
            field=models.TextField(default=0),
        ),
    ]
