# Generated by Django 3.2.9 on 2021-11-30 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20211130_0931'),
        ('web', '0002_alter_testimonial_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
    ]
