# Generated by Django 3.2.9 on 2021-11-25 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211125_1516'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.clients'),
        ),
        migrations.AddField(
            model_name='project',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/feature_image/'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_satisfied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='projects/thumbnails/'),
        ),
    ]
