# Generated by Django 3.2.9 on 2021-11-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_auto_20211127_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='completed_project_count',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pending_projects_count',
        ),
        migrations.RemoveField(
            model_name='project',
            name='satisfied_clients_count',
        ),
    ]
