# Generated by Django 3.2.9 on 2021-11-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_auto_20211127_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('apps', 'Apps'), ('template', 'Template'), ('ios', 'IOS'), ('ui/ux', 'UI/UX'), ('graphic', 'Graphic'), ('wireframes', 'Wireframes')], max_length=255),
        ),
    ]
