# Generated by Django 3.2.9 on 2021-11-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_alter_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('apps', 'Apps'), ('template', 'Template'), ('ios', 'IOS'), ('ui/ux', 'UI/UX'), ('graphic', 'Graphic'), ('wireframes', 'Wireframes')], max_length=255, null=True),
        ),
    ]
